name = "QuantumStateBase"
uuid = "73ce9c4f-35d1-4161-b9e6-26915895bfed"
authors = ["JingYu Ning <foldfelis@gmail.com> and contributors"]
version = "1.0.3"

[deps]
ClassicalOrthogonalPolynomials = "b30e2e7b-c4ee-47da-9d5f-2c5c27239acd"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"

[compat]
ClassicalOrthogonalPolynomials = "0.5"
DataDeps = "0.7"
KernelDensity = "0.6"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
